[package]
name = "binbox"
description = "POSIX core utilities written in Rust"
version = "0.0.1"

authors = ["Johnathan C Maudlin <jcmdln@gmail.com>"]
edition = "2018"
keywords = ["POSIX", "utilities", "coreutils", "binutils"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/jcmdln/binbox"

[[bin]]
name = "basename"
path = "usr.bin/basename/basename.rs"

[[bin]]
name = "false"
path = "usr.bin/false/false.rs"

# [[bin]]
# name = "sleep"
# path = "bin/sleep/sleep.rs"

[[bin]]
name = "true"
path = "usr.bin/true/true.rs"
