[package]
name = "binbox"
version = "0.1.0"
authors = ["jcmdln <jcmdln@gmail.com>"]
edition = "2018"

[dependencies]
basename = { path = "../basename" }
false = { path = "../false" }
true = { path = "../true" }
